version: '3.8'

services:
  postgres-wardrobe:
    image: postgres:15
    container_name: postgres-wardrobe
    environment:
      POSTGRES_DB: wardrobe_db
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
    ports:
      - "5433:5432"
    volumes:
      - wardrobe_pgdata:/var/lib/postgresql/data
    networks:
      - babycloset-network

  postgres-layette:
    image: postgres:15
    container_name: postgres-layette
    environment:
      POSTGRES_DB: layette_db
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
    ports:
      - "5434:5432"
    volumes:
      - layette_pgdata:/var/lib/postgresql/data
    networks:
      - babycloset-network

  postgres-exchange:
    image: postgres:15
    container_name: postgres-exchange
    environment:
      POSTGRES_DB: exchange_db
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
    ports:
      - "5435:5432"
    volumes:
      - exchange_pgdata:/var/lib/postgresql/data
    networks:
      - babycloset-network

  redpanda:
    image: docker.redpanda.com/redpandadata/redpanda:v23.3.10
    container_name: redpanda
    command:
      - redpanda
      - start
      - --overprovisioned
      - --smp 1
      - --memory 512M
      - --reserve-memory 0M
      - --node-id 0
      - --check=false
      - --kafka-addr PLAINTEXT://0.0.0.0:9092
      - --advertise-kafka-addr PLAINTEXT://redpanda:9092
    ports:
      - "9092:9092"
      - "9644:9644"
    networks:
      - babycloset-network

  redpanda-console:
    image: docker.redpanda.com/redpandadata/console:latest
    container_name: redpanda-console
    ports:
      - "8088:8080"
    environment:
      - KAFKA_BROKERS=redpanda:9092
    depends_on:
      - redpanda
    networks:
      - babycloset-network

networks:
  babycloset-network:
    driver: bridge

volumes:
  wardrobe_pgdata:
  layette_pgdata:
  exchange_pgdata:
