version: '3.8'

services:
  postgres-wardrobe:
    image: postgres:15
    container_name: postgres-wardrobe
    environment:
      POSTGRES_DB: wardrobe_db
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
    ports:
      - "5433:5432"
    volumes:
      - wardrobe_pgdata:/var/lib/postgresql/data
    networks:
      - babycloset-network

  postgres-layette:
    image: postgres:15
    container_name: postgres-layette
    environment:
      POSTGRES_DB: layette_db
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
    ports:
      - "5434:5432"
    volumes:
      - layette_pgdata:/var/lib/postgresql/data
    networks:
      - babycloset-network

  postgres-exchange:
    image: postgres:15
    container_name: postgres-exchange
    environment:
      POSTGRES_DB: exchange_db
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
    ports:
      - "5435:5432"
    volumes:
      - exchange_pgdata:/var/lib/postgresql/data
    networks:
      - babycloset-network

  zookeeper:
    image: confluentinc/cp-zookeeper:7.5.1
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    networks:
      - babycloset-network

  kafka:
    image: confluentinc/cp-kafka:7.5.1
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    networks:
      - babycloset-network

  wardrobe-service:
    build: ./wardrobe-service
    ports:
      - "8081:8080"
    depends_on:
      - postgres-wardrobe
      - kafka
    networks:
      - babycloset-network

  layette-service:
    build: ./layette-service
    ports:
      - "8082:8080"
    depends_on:
      - postgres-layette
      - kafka
    networks:
      - babycloset-network

  exchange-service:
    build: ./exchange-service
    ports:
      - "8083:8080"
    depends_on:
      - postgres-exchange
      - kafka
    networks:
      - babycloset-network

networks:
  babycloset-network:
    driver: bridge

volumes:
  wardrobe_pgdata:
  layette_pgdata:
  exchange_pgdata:
