server:
  port: 8080

spring:
  application:
    name: exchange-service

  datasource:
    url: jdbc:postgresql://postgres-exchange:5432/exchange_db
    username: admin
    password: admin
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  kafka:
    bootstrap-servers: kafka:9092

logging:
  level:
    org.springframework.kafka: info
