server:
  port: 8081

spring:
  application:
    name: wardrobe-service

  datasource:
    url: jdbc:postgresql://localhost:5433/wardrobe_db
    username: admin
    password: admin
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  kafka:
    bootstrap-servers: localhost:9092

logging:
  level:
    org.springframework.kafka: info
